/* Generated by Yosys 0.57+125 (git sha1 83fa0448107e31360393366ba4bef15a713ba5f4, clang++ 19.1.7 -fPIC -O3) */

module BitStuff_1(clock_1, reset_1, a_1, b_1, c_1, out_1);
  input clock_1;
  wire clock_1;
  input reset_1;
  wire reset_1;
  input [7:0] a_1;
  wire [7:0] a_1;
  input [3:0] b_1;
  wire [3:0] b_1;
  input [1:0] c_1;
  wire [1:0] c_1;
  output [9:0] out_1;
  wire [9:0] out_1;
  wire [4:0] _00_;
  wire [4:0] _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire [3:0] _04_;
  wire [3:0] _05_;
  wire [3:0] _06_;
  wire [3:0] _07_;
  wire [7:0] _08_;
  wire [3:0] _09_;
  wire [4:0] _10_;
  assign _00_ = { 3'h0 , c_1 };
  assign _01_ = _10_ + _00_;
  assign _02_ = { 3'h0 , _01_ };
  assign _03_ = _02_ + a_1;
  assign _04_ = _03_ >> 4;
  assign _06_ = _03_ >> 0;
  assign _07_ = _06_ | b_1;
  assign _08_ = { _04_ , _07_ };
  assign _05_ = a_1 >> 0;
  assign out_1 = { 2'h0 , _08_ };
  assign _09_ = _05_ & b_1;
  assign _10_ = { 1'h0 , _09_ };
endmodule
